const districts = [
  { id: 'harbor', name: 'Havnefronten', detail: 'containere // hurtige handler', flavor: 'Salt i luften og varer, der skifter haender.' },
  { id: 'arcade', name: 'Pixel Arcade', detail: 'lysreklamer // lav profil', flavor: 'Spilmaskinerne larmer hoejere end rygterne.' },
  { id: 'market', name: 'Natmarkedet', detail: 'crowds // mange oejne', flavor: 'Alle saelger noget. Ikke alle kender prisen.' },
  { id: 'heights', name: 'East Heights', detail: 'penthouse // hoej risiko', flavor: 'Udsigten er dyr, men kunderne er rige.' }
];
const goods = [
  { id: 'synth', name: 'Synth-piller', icon: '✦', base: 180, volatility: 80 },
  { id: 'neon', name: 'Neon-støv', icon: '◈', base: 340, volatility: 150 },
  { id: 'ghost', name: 'Ghost-chips', icon: '◉', base: 620, volatility: 260 },
  { id: 'juice', name: 'Boost-juice', icon: '△', base: 95, volatility: 45 }
];
const customerTemplates = [
  ['Rex', 'buddet', 'hurtig handel'], ['Vanta', 'klubejer', 'betaler godt'], ['Milo', 'samler', 'stiller krav'], ['Kira', 'natugle', 'vil forhandle'], ['Juno', 'fixer', 'ingen spørgsmål'], ['Sable', 'VIP-kunde', 'meget diskret'], ['Nox', 'gadefotograf', 'kender alle'], ['Ivy', 'promoter', 'køber stort']
];
const contractTemplates = [{ title: 'Hurtig levering', target: 3, reward: 650 }, { title: 'Markedskonge', target: 5, reward: 900 }, { title: 'Få gang i byen', target: 8, reward: 1200 }];
const customizationItems = [
  { id: 'cap', category: 'HATTE', name: 'Neon cap', price: 220, className: 'hat-cap', description: 'En lav profil med høj glød.' },
  { id: 'crown', category: 'HATTE', name: 'Chrome crown', price: 650, className: 'hat-crown', description: 'Til kunder, der skal huske dig.' },
  { id: 'snapback', category: 'HATTE', name: 'Block snapback', price: 390, className: 'hat-snapback', description: 'Skygge i ansigtet. Respekt i gaden.' },
  { id: 'blackcap', category: 'HATTE', name: 'Black low cap', price: 520, className: 'hat-blackcap', description: 'Sort kasket til diskrete handler.' },
  { id: 'chain', category: 'ACCESSORIES', name: 'Guld chain', price: 1250, className: 'chain-gold', description: 'Tung glans omkring halsen.' },
  { id: 'doublechain', category: 'ACCESSORIES', name: 'Double gold chain', price: 2400, className: 'chain-double', description: 'To kæder. Én klar besked.' },
  { id: 'hoodie', category: 'TRØJER', name: 'Night hoodie', price: 420, className: 'shirt-hoodie', description: 'Blød tekstil. Hård attitude.' },
  { id: 'varsity', category: 'TRØJER', name: 'District varsity', price: 780, className: 'shirt-varsity', description: 'Officiel stil fra gaden.' },
  { id: 'cargo', category: 'BUKSER', name: 'Cargo pants', price: 360, className: 'pants-cargo', description: 'Flere lommer til flere planer.' },
  { id: 'chrome', category: 'BUKSER', name: 'Chrome denim', price: 560, className: 'pants-chrome', description: 'Reflekterer lys og opmærksomhed.' },
  { id: 'wave', category: 'EMOTES', name: 'Street wave', price: 180, className: 'emote-wave', description: 'Et hurtigt signal til dine venner.' },
  { id: 'money', category: 'EMOTES', name: 'Cash flash', price: 480, className: 'emote-money', description: 'Lad pengene tale for dig.' },
  { id: 'textile', category: 'TEXTILER', name: 'Lime textile pack', price: 300, className: 'textile-lime', description: 'Et komplet stofskift til dit outfit.' },
  { id: 'carbon', category: 'TEXTILER', name: 'Carbon weave', price: 900, className: 'textile-carbon', description: 'Mørk vævning med premium finish.' }
];
const businessUpgrades = [
  { id: 'stash', name: 'Skjult lager', price: 1100, description: '+8 lagerpladser til dine ruter.', effect: '+8 SLOTS' },
  { id: 'network', name: 'Bedre netværk', price: 1600, description: '+12% betaling fra alle kunder.', effect: '+12% PRIS' },
  { id: 'cleaner', name: 'Renere rute', price: 1350, description: 'Køb varer med mindre opmærksomhed.', effect: '-35% RISIKO' }
];
let customers = [];
function generateCustomers() { const shuffled = [...customerTemplates].sort(() => Math.random() - .5); const positions = []; customers = shuffled.slice(0, 5).map((template, index) => { let position; do { position = { x: 17 + Math.random() * 70, y: 35 + Math.random() * 44 }; } while (positions.some((item) => Math.hypot(item.x - position.x, item.y - position.y) < 15)); positions.push(position); const wants = [...goods].sort(() => Math.random() - .5).slice(0, 2).map((good) => good.id); return { id: `${template[0].toLowerCase()}-${Date.now()}-${index}`, name: template[0], role: template[1], mood: template[2], x: position.x, y: position.y, wants, wanted: wants[0], quantity: 1 + Math.floor(Math.random() * 3), budget: 1.12 + Math.random() * .46, patience: 3 + Math.floor(Math.random() * 3), trust: 45 + Math.floor(Math.random() * 50), direction: Math.random() * Math.PI * 2 }; }); }
const state = { cash: 2500, day: 1, rep: 12, risk: 18, inventory: {}, location: 0, prices: {}, logs: [], player: { x: 50, y: 73 }, keys: {}, nearbyCustomer: null, activeTab: 'sell', inWorld: false, saleTarget: null, policeChase: null, arrestMinigame: null, loan: 0, loanRate: .08, postMessages: [], nightSales: 0, nightGoal: 3, nightBonus: 500, taskSales: 0, taskBuys: 0, taskTravel: 0, combo: 0, comboBest: 0, contract: null, ownedCustomizations: [], ownedUpgrades: [], equipped: { hat: '', shirt: '', pants: '', emote: '', textile: '', accessory: '' }, shopCategory: 'ALLE' };
const $ = (selector) => document.querySelector(selector);
const format = (number) => `${Math.round(number).toLocaleString('da-DK')} kr`;
window.getGameSaveData = () => ({ cash: state.cash, day: state.day, rep: state.rep, risk: state.risk, inventory: state.inventory, location: state.location, prices: state.prices, player: state.player, loan: state.loan, loanRate: state.loanRate, postMessages: state.postMessages, nightSales: state.nightSales, nightGoal: state.nightGoal, nightBonus: state.nightBonus, taskSales: state.taskSales, taskBuys: state.taskBuys, taskTravel: state.taskTravel, combo: state.combo, comboBest: state.comboBest, contract: state.contract, ownedCustomizations: state.ownedCustomizations, ownedUpgrades: state.ownedUpgrades, equipped: state.equipped, logs: state.logs });
window.applyGameSaveData = (saved) => { if (!saved || typeof saved !== 'object') return; Object.assign(state, { cash: Number(saved.cash) || 2500, day: Number(saved.day) || 1, rep: Number(saved.rep) || 12, risk: Number(saved.risk) || 18, inventory: saved.inventory || {}, location: Number(saved.location) || 0, prices: saved.prices || {}, player: saved.player || { x: 50, y: 73 }, loan: Number(saved.loan) || 0, loanRate: Number(saved.loanRate) || .08, postMessages: saved.postMessages || [], nightSales: Number(saved.nightSales) || 0, nightGoal: Number(saved.nightGoal) || 3, nightBonus: Number(saved.nightBonus) || 500, taskSales: Number(saved.taskSales) || 0, taskBuys: Number(saved.taskBuys) || 0, taskTravel: Number(saved.taskTravel) || 0, combo: Number(saved.combo) || 0, comboBest: Number(saved.comboBest) || 0, contract: saved.contract || null, ownedCustomizations: saved.ownedCustomizations || [], ownedUpgrades: saved.ownedUpgrades || [], equipped: saved.equipped || state.equipped, logs: saved.logs || [] }); state.location = Math.max(0, Math.min(districts.length - 1, state.location)); state.inWorld = true; state.saleTarget = null; generateCustomers(); if (!Object.keys(state.prices).length) makePrices(); checkPostDeadlines(); render(); };
function makePrices() { goods.forEach((good) => { state.prices[good.id] = districts.map(() => Math.max(25, Math.round(good.base + (Math.random() - .5) * good.volatility * 2))); }); }
function addLog(text, tone = '') { state.logs.unshift({ text, tone }); state.logs = state.logs.slice(0, 4); renderLog(); }
function toast(text) { const node = $('#toast'); node.textContent = text; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2200); }
function renderDistricts() { $('#districtGrid').innerHTML = districts.map((district, index) => `<button class="district ${index === state.location ? 'active' : ''}" data-location="${index}"><span class="district-art"></span><h3>${district.name}</h3><p>${district.detail}</p></button>`).join(''); document.querySelectorAll('.district').forEach((button) => button.addEventListener('click', () => { state.location = Number(button.dataset.location); render(); addLog(`Flyttet til ${districts[state.location].name.toLowerCase()}.`); })); }
function clearMovementInput() { state.keys = {}; }
function renderMap() { $('#mapPosition').textContent = districts[state.location].name.toUpperCase(); $('#mapGrid').innerHTML = districts.map((district, index) => `<button class="map-district ${index === state.location ? 'active' : ''}" data-map-location="${index}"><span class="map-district-art"></span><i>${String(index + 1).padStart(2, '0')}</i><b>${district.name}</b><small>${district.detail}</small><em>${index === state.location ? 'GÅ IND HER' : 'VÆLG OMRÅDE'}</em></button>`).join(''); document.querySelectorAll('[data-map-location]').forEach((button) => button.addEventListener('click', () => { clearMovementInput(); const destination = Number(button.dataset.mapLocation); if (destination !== state.location) state.taskTravel += 1; state.location = destination; state.player = { x: 50, y: 73 }; state.nearbyCustomer = null; state.saleTarget = null; state.inWorld = true; generateCustomers(); makePrices(); addLog(`Gik ind i ${districts[state.location].name.toLowerCase()}.`); closeMap(); render(); toast(`Du er nu i ${districts[state.location].name}`); })); }
function openMap() { clearMovementInput(); state.inWorld = false; setTab('sell'); renderMap(); $('#mapOverlay').hidden = false; document.body.classList.add('map-open'); }
function closeMap() { $('#mapOverlay').hidden = true; document.body.classList.remove('map-open'); }
function renderGoods() { $('#goodsList').innerHTML = goods.map((good) => { const price = state.prices[good.id][state.location]; const owned = state.inventory[good.id] || 0; const delta = price > good.base ? '+' : '-'; return `<div class="good-row"><div class="good-name"><span class="good-icon">${good.icon}</span><span>${good.name}</span></div><strong class="price">${format(price)}</strong><span class="trend ${delta === '+' ? 'up' : ''}">${delta}${Math.abs(Math.round((price / good.base - 1) * 100))}% marked</span><span class="owned">LAGER: ${owned} / ${inventoryCapacity()}</span><div class="trade-actions"><button data-action="buy" data-good="${good.id}" data-amount="1">×1</button><button data-action="buy" data-good="${good.id}" data-amount="5">×5</button><button data-action="buy" data-good="${good.id}" data-amount="10">×10</button></div></div>`; }).join(''); document.querySelectorAll('.trade-actions button').forEach((button) => button.addEventListener('click', () => trade(button.dataset.action, button.dataset.good, Number(button.dataset.amount)))); }
function applyAvatarStyle(element) { if (!element) return; customizationItems.forEach((item) => element.classList.remove(item.className)); Object.values(state.equipped).forEach((itemId) => { const item = customizationItems.find((entry) => entry.id === itemId); if (item) element.classList.add(item.className); }); }
function renderUpgrades() { $('#businessUpgrades').innerHTML = businessUpgrades.map((upgrade) => { const owned = state.ownedUpgrades.includes(upgrade.id); return `<div class="upgrade-item ${owned ? 'owned' : ''}"><div><b>${upgrade.name}</b><small>${upgrade.description}</small></div><span>${upgrade.effect}</span><button data-upgrade="${upgrade.id}" ${owned ? 'disabled' : ''}>${owned ? 'AKTIV' : format(upgrade.price)}</button></div>`; }).join(''); document.querySelectorAll('[data-upgrade]').forEach((button) => button.addEventListener('click', () => buyUpgrade(button.dataset.upgrade))); }
function buyUpgrade(id) { const upgrade = businessUpgrades.find((item) => item.id === id); if (!upgrade || state.ownedUpgrades.includes(id)) return; if (state.cash < upgrade.price) { toast('Ikke nok kontanter'); return; } state.cash -= upgrade.price; state.ownedUpgrades.push(id); addLog(`Opgraderede forretningen: ${upgrade.name.toLowerCase()}.`); toast(`${upgrade.name} er aktiv`); render(); }
function sellCustomization(id) { const item = customizationItems.find((entry) => entry.id === id); if (!item || !state.ownedCustomizations.includes(id)) return; const refund = Math.floor(item.price * .6); state.cash += refund; state.ownedCustomizations = state.ownedCustomizations.filter((itemId) => itemId !== id); Object.keys(state.equipped).forEach((slot) => { if (state.equipped[slot] === id) state.equipped[slot] = ''; }); addLog(`Solgte ${item.name.toLowerCase()} for ${format(refund)}.`); toast(`${item.name} solgt for ${format(refund)}`); render(); setTab('shop'); }
function renderProfile() { const equippedItems = customizationItems.filter((item) => Object.values(state.equipped).includes(item.id)); $('#profileAvatar').textContent = window.profileUserEmail ? window.profileUserEmail[0].toUpperCase() : '?'; $('#profileEmail').textContent = window.profileUserEmail || 'Gæstespiller'; $('#profileStatus').textContent = window.profileUserEmail ? 'Din rute gemmes automatisk i skyen.' : 'Fortsæt med login for at gemme i skyen.'; $('#profileLogout').hidden = !window.profileUserEmail; $('#profileReset').hidden = !window.profileUserEmail; $('#profileOutfitName').textContent = equippedItems.length ? equippedItems.map((item) => item.name).join(' · ') : 'Standard look'; $('#profileOutfitText').textContent = equippedItems.length ? 'Dit aktive outfit vises i byen.' : 'Vælg items nedenfor eller åbn shoppen.'; applyAvatarStyle($('#profileOutfitAvatar')); const ownedItems = customizationItems.filter((item) => state.ownedCustomizations.includes(item.id)); $('#profileItems').innerHTML = ownedItems.length ? ownedItems.map((item) => `<button class="profile-item ${Object.values(state.equipped).includes(item.id) ? 'active' : ''}" data-profile-item="${item.id}">${item.name}<small>${Object.values(state.equipped).includes(item.id) ? 'AKTIV' : 'EQUIP'}</small></button>`).join('') : '<span class="profile-empty">Ingen købte items endnu.</span>'; $('#profileUpgrades').innerHTML = businessUpgrades.filter((item) => state.ownedUpgrades.includes(item.id)).map((item) => `<span class="profile-upgrade">${item.name} <b>${item.effect}</b></span>`).join('') || '<span class="profile-empty">Ingen forretnings-opgraderinger endnu.</span>'; document.querySelectorAll('[data-profile-item]').forEach((button) => button.addEventListener('click', () => { customize(button.dataset.profileItem); setTab('profile'); })); }
function renderShop() { renderUpgrades(); const categories = ['ALLE', ...new Set(customizationItems.map((item) => item.category))]; $('#shopFilters').innerHTML = categories.map((category) => `<button class="shop-filter ${state.shopCategory === category ? 'active' : ''}" data-shop-category="${category}">${category}</button>`).join(''); const visibleItems = state.shopCategory === 'ALLE' ? customizationItems : customizationItems.filter((item) => item.category === state.shopCategory); $('#shopItems').innerHTML = visibleItems.map((item) => { const owned = state.ownedCustomizations.includes(item.id); const equipped = Object.values(state.equipped).includes(item.id); return `<div class="shop-item ${equipped ? 'equipped' : ''}"><span class="shop-swatch ${item.className}"></span><div><b>${item.name}</b><small>${item.description}</small></div><button data-customization="${item.id}">${equipped ? 'AKTIV' : owned ? 'EQUIP' : format(item.price)}</button></div>`; }).join(''); document.querySelectorAll('[data-shop-category]').forEach((button) => button.addEventListener('click', () => { state.shopCategory = button.dataset.shopCategory; renderShop(); })); document.querySelectorAll('[data-customization]').forEach((button) => button.addEventListener('click', () => customize(button.dataset.customization))); const equippedItems = customizationItems.filter((item) => Object.values(state.equipped).includes(item.id)); $('#equippedName').textContent = equippedItems.length ? equippedItems.map((item) => item.name).join(' · ') : 'Standard look'; $('#equippedText').textContent = equippedItems.length ? 'Dit outfit er synligt i gaden og for dine kunder.' : 'Din stil vises for alle kunder i byen.'; applyAvatarStyle($('#player')); applyAvatarStyle($('#shopAvatar')); }
function customize(id) { const item = customizationItems.find((entry) => entry.id === id); if (!item) return; if (!state.ownedCustomizations.includes(id)) { if (state.cash < item.price) { toast('Ikke nok kontanter'); return; } state.cash -= item.price; state.ownedCustomizations.push(id); addLog(`Købte ${item.name.toLowerCase()} for ${format(item.price)}.`); toast(`${item.name} købt`); } const slot = item.category === 'HATTE' ? 'hat' : item.category === 'TRØJER' ? 'shirt' : item.category === 'BUKSER' ? 'pants' : item.category === 'EMOTES' ? 'emote' : item.category === 'ACCESSORIES' ? 'accessory' : 'textile'; state.equipped[slot] = id; toast(`${item.name} er nu equipet`); render(); setTab('explore'); }
function inventoryTotal() { return Object.values(state.inventory).reduce((sum, value) => sum + value, 0); }
function inventoryCapacity() { return 24 + (state.ownedUpgrades.includes('stash') ? 8 : 0); }
function trade(action, id, amount = 1) { const price = state.prices[id][state.location]; const good = goods.find((item) => item.id === id); if (action === 'buy') { const available = Math.min(amount, inventoryCapacity() - inventoryTotal(), Math.floor(state.cash / price)); if (available < 1) { toast('Ikke nok kontanter eller lagerplads'); return; } state.cash -= price * available; state.inventory[id] = (state.inventory[id] || 0) + available; state.taskBuys += available; state.risk = Math.min(99, state.risk + Math.max(1, Math.round(available * (state.ownedUpgrades.includes('cleaner') ? .65 : 1)))); toast(`${available} × ${good.name} lagt i lager`); addLog(`Købte ${available} × ${good.name.toLowerCase()} for ${format(price * available)}.`); render(); } }
function renderStreet() { $('#streetLocation').textContent = districts[state.location].name.toUpperCase(); $('#player').style.left = `${state.player.x}%`; $('#player').style.top = `${state.player.y}%`; const police = $('#policeNpc'); if (state.policeChase) { police.hidden = false; police.style.left = `${state.policeChase.x}%`; police.style.top = `${state.policeChase.y}%`; police.style.right = 'auto'; } else if ($('#wastedOverlay').hidden) police.hidden = true; $('#customerLayer').innerHTML = customers.map((customer) => { const wanted = goods.find((good) => good.id === customer.wanted); return `<button class="customer ${state.nearbyCustomer === customer.id ? 'nearby' : ''}" data-customer="${customer.id}" style="left:${customer.x}%;top:${customer.y}%"><span class="customer-head"></span><b>${customer.name}</b><small>${customer.role} // ${wanted.icon}</small></button>`; }).join(''); document.querySelectorAll('.customer').forEach((node) => node.addEventListener('click', () => { $('#streetPrompt').textContent = 'Kunden er dér — gå derhen med WASD eller pilene'; $('#streetStage').focus(); })); updateNearby(); }
function moveCustomers() { customers.forEach((customer) => { if (customer.id === state.nearbyCustomer) return; if (Math.random() < .25) customer.direction += (Math.random() - .5) * 1.7; const pace = .7 + Math.random() * .9; customer.x = Math.max(12, Math.min(88, customer.x + Math.cos(customer.direction) * pace)); customer.y = Math.max(34, Math.min(80, customer.y + Math.sin(customer.direction) * pace * .55)); }); const occupied = customers.map((customer) => ({ x: customer.x, y: customer.y })); customers.forEach((customer, index) => { const collision = occupied.some((position, otherIndex) => otherIndex !== index && Math.hypot(position.x - customer.x, position.y - customer.y) < 8); if (collision) customer.direction += Math.PI * .7; }); renderStreet(); }
function updateNearby() { const nearby = customers.find((customer) => Math.hypot(customer.x - state.player.x, customer.y - state.player.y) < 12); state.nearbyCustomer = nearby ? nearby.id : null; const prompt = $('#streetPrompt'); const button = $('#interactBtn'); if (nearby) { prompt.textContent = `${nearby.name.toUpperCase()} ER KLAR // TRYK E FOR AT ÅBNE SALG`; button.disabled = inventoryTotal() === 0; } else { prompt.textContent = 'Gå rundt og find en kunde'; button.disabled = true; } document.querySelectorAll('.customer').forEach((node) => node.classList.toggle('nearby', node.dataset.customer === state.nearbyCustomer)); }
function interact() { const customer = customers.find((item) => item.id === state.nearbyCustomer); if (!customer) return; if (inventoryTotal() === 0) { toast('Dit lager er tomt'); return; } state.saleTarget = customer.id; setTab('sell'); renderQuickSale(); toast(`Klar til salg med ${customer.name}`); }
function triggerArrest() { state.policeChase = null; state.arrestMinigame = null; state.inventory = {}; state.saleTarget = null; state.postMessages.push({ id: `fine-${Date.now()}`, subject: 'Bøde og beslaglæggelse', body: 'Du er blevet taget af politiet. Din bøde skal betales inden 30 minutter. Hvis den ikke betales, trækkes beløbet automatisk med 5% rente.', amount: 5000, createdAt: Date.now(), dueAt: Date.now() + 30 * 60 * 1000, paid: false, autoCollected: false }); $('#escapeOverlay').hidden = true; $('#policeNpc').hidden = false; $('#wastedOverlay').hidden = false; $('#streetPrompt').textContent = 'POLITIET HAR FAT I DIG // RUTEN ER LUKKET'; addLog('Du blev taget af politiet. Lageret blev beslaglagt og du fik en bøde på 5.000 kr.'); render(); }
function startArrestMinigame() { if (state.arrestMinigame) return; state.policeChase = null; state.arrestMinigame = { elapsed: 0, duration: 1.5, marker: 0, direction: 1, zoneStart: .38, zoneEnd: .62 }; $('#policeNpc').hidden = true; $('#escapeOverlay').hidden = false; $('#streetPrompt').textContent = 'TRYK E I DET GRØNNE FELT'; }
function resolveArrestMinigame() { const game = state.arrestMinigame; if (!game) return; const success = game.marker >= game.zoneStart && game.marker <= game.zoneEnd; state.arrestMinigame = null; $('#escapeOverlay').hidden = true; if (success) { state.player.x = Math.max(10, Math.min(90, state.player.x + (state.player.x < 50 ? -18 : 18))); state.policeChase = { x: Math.max(8, Math.min(92, state.player.x + (state.player.x < 50 ? 38 : -38))), y: state.player.y, elapsed: -3 }; $('#streetPrompt').textContent = 'DU SLAP FRI // 3 SEKUNDERS FORSPRING'; toast('Du slap fri — løb!'); addLog('Du ramte timingen og fik 3 sekunders forspring.'); renderStreet(); } else triggerArrest(); }
function startPoliceChase() { if (state.policeChase || !state.inWorld) return; state.policeChase = { x: Math.max(8, Math.min(92, state.player.x + (state.player.x < 50 ? 38 : -38))), y: state.player.y, elapsed: 0 }; $('#policeNpc').hidden = false; $('#streetPrompt').textContent = 'POLITIET JAGER DIG // LØB VÆK I 10 SEKUNDER'; toast('POLITIET KOMMER — LØB!'); addLog('Politiet har set dig. Du har 10 sekunder til at slippe væk.'); renderStreet(); }
function updatePoliceChase(delta) { if (state.arrestMinigame) { const game = state.arrestMinigame; game.elapsed += delta / 1000; game.marker += game.direction * delta / 1000 * .95; if (game.marker >= game.zoneEnd) { triggerArrest(); return; } $('#escapeMarker').style.left = `${game.marker * 100}%`; $('#escapeTimer').textContent = `${Math.max(0, game.duration - game.elapsed).toFixed(1)} sekunder`; return; } if (!state.policeChase) return; if (!state.inWorld || !$('#mapOverlay').hidden) { state.policeChase = null; $('#policeNpc').hidden = true; return; } const chase = state.policeChase; chase.elapsed += delta / 1000; const dx = state.player.x - chase.x; const dy = state.player.y - chase.y; const distance = Math.hypot(dx, dy); if (distance < 4) { startArrestMinigame(); return; } if (chase.elapsed >= 10) { state.policeChase = null; $('#policeNpc').hidden = true; $('#streetPrompt').textContent = 'DU SLAP VÆK // FIND EN KUNDE'; toast('Du slap væk fra politiet'); addLog('Politiet mistede dig efter 10 sekunder.'); renderStreet(); return; } const speed = .007 * delta; chase.x += dx / (distance || 1) * speed; chase.y += dy / (distance || 1) * speed; const police = $('#policeNpc'); police.style.left = `${chase.x}%`; police.style.top = `${chase.y}%`; police.style.right = 'auto'; }
function sellItem(id) { const customer = customers.find((item) => item.id === state.saleTarget); const good = goods.find((item) => item.id === id); if (!customer || !good || (state.inventory[id] || 0) < 1) return; const accepted = customer.wants.includes(id); const premium = id === customer.wanted ? customer.budget : accepted ? customer.budget * .78 : customer.budget * .55; const networkBonus = state.ownedUpgrades.includes('network') ? 1.12 : 1; const price = Math.round(state.prices[id][state.location] * premium * networkBonus * (1 + Math.min(state.combo, 5) * .04)); state.inventory[id] -= 1; customer.quantity -= 1; state.cash += price; state.taskSales += 1; state.combo += 1; state.comboBest = Math.max(state.comboBest, state.combo); state.rep += accepted ? 1 : 0; state.risk = Math.max(0, state.risk - 1); customer.trust = Math.min(100, customer.trust + (accepted ? 7 : 2)); customer.patience = Math.min(5, customer.patience + 1); state.nightSales += 1; toast(`${good.name} solgt · ${state.combo}x combo`); addLog(`Solgte ${good.name.toLowerCase()} til ${customer.name} for ${format(price)} (${state.combo}x combo).`, 'good'); if (state.contract && state.taskSales >= state.contract.target) { state.cash += state.contract.reward; addLog(`Kontrakt fuldført: ${state.contract.title} (+${format(state.contract.reward)}).`); toast(`KONTRAKT FULDFØRT +${format(state.contract.reward)}`); state.contract = null; } if (state.nightSales === state.nightGoal) { state.cash += state.nightBonus; state.rep += 2; toast(`NATTERMÅL FULDFØRT +${format(state.nightBonus)}`); addLog(`Nattermål fuldført. Bonus på ${format(state.nightBonus)}.`); } if (customer.quantity <= 0 || inventoryTotal() === 0) state.saleTarget = null; render(); if (Math.random() < .05) startPoliceChase(); }
function renderQuickSale() { const customer = customers.find((item) => item.id === state.saleTarget); if (!customer) { $('#saleOverlay').hidden = true; return; } const wanted = goods.find((good) => good.id === customer.wanted); $('#saleOverlay').hidden = false; $('#quickSaleTitle').textContent = `${customer.name} // ${customer.role}`; $('#quickSaleText').textContent = `Ordre: ${customer.quantity} enhed${customer.quantity === 1 ? '' : 'er'}. ${wanted.name} er favoritvaren og giver bedst pris.`; $('#quickSaleGoods').innerHTML = goods.map((good) => { const owned = state.inventory[good.id] || 0; const accepted = customer.wants.includes(good.id); const price = Math.round(state.prices[good.id][state.location] * (good.id === customer.wanted ? customer.budget : accepted ? customer.budget * .78 : customer.budget * .55)); return `<button class="quick-sale-good ${good.id === customer.wanted ? 'wanted' : ''}" data-quick-sell="${good.id}" ${owned ? '' : 'disabled'}><span>${good.icon}</span><b>${good.name}</b><small>${owned} på lager · ${good.id === customer.wanted ? 'favorit · ' : accepted ? 'accepteres · ' : 'lavere tilbud · '}${format(price)}</small></button>`; }).join(''); document.querySelectorAll('[data-quick-sell]').forEach((button) => button.addEventListener('click', () => sellItem(button.dataset.quickSell))); }
function closeSale() { state.saleTarget = null; $('#saleOverlay').hidden = true; render(); toast('Handel lukket — du kan gå videre'); }
function renderBank() { const interest = Math.ceil(state.loan * state.loanRate); $('#loanBalance').textContent = format(state.loan); $('#loanInterest').textContent = state.loan ? `Næste dag koster renten ${format(interest)}.` : 'Ingen aktiv rente.'; $('#loanRate').textContent = `${Math.round(state.loanRate * 100)}%`; $('#nextInterest').textContent = format(interest); $('#repayLoan').disabled = state.loan <= 0 || state.cash <= 0; }
function takeLoan() { const amount = Math.floor(Number($('#loanAmount').value) || 0); if (amount < 100) { toast('Lånet skal være mindst 100 kr.'); return; } state.cash += amount; state.loan += amount; addLog(`Tog et kviklån på ${format(amount)}. Renterne vokser ved dagsskift.`); toast(`+${format(amount)} lånt`); render(); setTab('bank'); }
function repayLoan() { if (state.loan <= 0) return; const payment = Math.min(state.cash, state.loan); if (payment <= 0) { toast('Du har ingen kontanter til at betale med'); return; } state.cash -= payment; state.loan -= payment; addLog(`Betalte ${format(payment)} tilbage til banken.`); toast(`Betalte ${format(payment)} tilbage`); render(); setTab('bank'); }
function checkPostDeadlines() { const now = Date.now(); state.postMessages.forEach((message) => { if (!message.paid && now >= message.dueAt) { const total = Math.ceil(message.amount * 1.05); state.cash -= total; message.paid = true; message.autoCollected = true; addLog(`POST trak automatisk ${format(total)} for politibøden inkl. 5% rente.`); toast(`POST: -${format(total)} inkl. rente`); } }); }
function renderPost() { checkPostDeadlines(); $('#postCount').textContent = state.postMessages.filter((message) => !message.paid).length; $('#postList').innerHTML = state.postMessages.length ? state.postMessages.slice().reverse().map((message) => { const due = message.paid ? message.autoCollected ? 'TRUKKET AUTOMATISK' : 'BETALT' : `FORFALDER ${new Date(message.dueAt).toLocaleTimeString('da-DK', { hour: '2-digit', minute: '2-digit' })}`; return `<article class="post-letter ${message.paid ? 'paid' : 'unpaid'}"><div class="post-letter-top"><span class="post-seal">POLITI</span><small>${new Date(message.createdAt).toLocaleDateString('da-DK')}</small></div><h3>${message.subject}</h3><p>${message.body}</p><div class="post-letter-bottom"><strong>${format(message.paid && message.autoCollected ? Math.ceil(message.amount * 1.05) : message.amount)}</strong><span>${due}</span>${!message.paid ? `<button data-pay-post="${message.id}" ${state.cash < message.amount ? 'disabled' : ''}>BETAL NU</button>` : ''}</div></article>`; }).join('') : '<div class="post-empty">Din postkasse er tom.</div>'; document.querySelectorAll('[data-pay-post]').forEach((button) => button.addEventListener('click', () => payPostFine(button.dataset.payPost))); }
function payPostFine(id) { const message = state.postMessages.find((item) => item.id === id); if (!message || message.paid) return; if (state.cash < message.amount) { toast('Du har ikke penge nok til bøden'); return; } state.cash -= message.amount; message.paid = true; addLog(`Betalte politibøde på ${format(message.amount)} via POST.`); toast('Bøde betalt'); render(); setTab('post'); }
function setTab(tab) { if (tab === 'explore') tab = 'sell'; state.activeTab = tab; document.querySelectorAll('.game-tab').forEach((button) => button.classList.toggle('active', button.dataset.tab === tab)); $('.explore-view').hidden = !(tab === 'sell' && state.inWorld); $('#sellView').hidden = tab !== 'sell' || state.inWorld; $('#shopView').hidden = tab !== 'shop'; $('#profileView').hidden = tab !== 'profile'; $('#bankView').hidden = tab !== 'bank'; $('#postView').hidden = tab !== 'post'; if (tab === 'sell' && !state.inWorld) renderSellPanel(); if (tab === 'shop') renderShop(); if (tab === 'profile') renderProfile(); if (tab === 'bank') renderBank(); if (tab === 'post') renderPost(); }
function renderSellPanel() { const customer = customers.find((item) => item.id === state.saleTarget); const wanted = customer && goods.find((good) => good.id === customer.wanted); $('#sellLocation').textContent = customer ? `KONTAKT: ${customer.name.toUpperCase()}` : 'INGEN KUNDE VALGT'; $('#contactAvatar').textContent = customer ? customer.name[0] : '?'; $('#contactName').textContent = customer ? customer.name : 'Vælg en kunde'; $('#contactRole').textContent = customer ? `${customer.role} // ${customer.mood}. Ordre: ${customer.quantity} enheder. ${wanted.name} er favorit; ${customer.wants.length - 1} anden vare accepteres også.` : 'Vælg en kunde fra området for at åbne en direkte handel.'; $('#contactSignal').textContent = customer ? 'ONLINE // KØBER NU' : 'OFFLINE'; $('#contactTrust').textContent = customer ? `${customer.trust}%` : '--'; $('#contactPatience').textContent = customer ? `${customer.patience}/5` : '--'; $('#customerList').innerHTML = customers.map((item) => `<button class="customer-contact ${item.id === state.saleTarget ? 'active' : ''}" data-contact="${item.id}"><span>${item.name[0]}</span><b>${item.name}</b><small>${item.role}</small><em>${item.quantity} enheder</em></button>`).join(''); document.querySelectorAll('[data-contact]').forEach((button) => button.addEventListener('click', () => { state.saleTarget = button.dataset.contact; renderSellPanel(); })); $('#sellGoodsList').innerHTML = goods.map((good) => { const owned = state.inventory[good.id] || 0; const price = customer ? Math.round(state.prices[good.id][state.location] * (customer.wants.includes(good.id) ? customer.budget : customer.budget * .45)) : Math.round(state.prices[good.id][state.location] * 1.08); const isWanted = customer && good.id === customer.wanted; const accepted = customer && customer.wants.includes(good.id); return `<div class="sell-good-row ${isWanted ? 'wanted' : ''} ${accepted && !isWanted ? 'accepted' : ''}"><span class="good-icon">${good.icon}</span><div><b>${good.name} ${isWanted ? '<em>KUNDENS ØNSKE</em>' : accepted ? '<em>ACCEPTERES</em>' : ''}</b><small>${owned} på lager · tilbud ${format(price)}</small></div><button data-sell-good="${good.id}" ${customer && owned ? '' : 'disabled'}>SÆLG 1 <b>→</b></button></div>`; }).join(''); document.querySelectorAll('[data-sell-good]').forEach((button) => button.addEventListener('click', () => sellItem(button.dataset.sellGood))); }
function movePlayer(key) { const speed = 4; if (key === 'arrowleft' || key === 'a') state.player.x = Math.max(10, state.player.x - speed); if (key === 'arrowright' || key === 'd') state.player.x = Math.min(90, state.player.x + speed); if (key === 'arrowup' || key === 'w') state.player.y = Math.max(30, state.player.y - speed); if (key === 'arrowdown' || key === 's') state.player.y = Math.min(84, state.player.y + speed); updateNearby(); renderStreet(); }
function updatePlayerMovement(delta) { if (state.activeTab !== 'sell' || !state.inWorld || !$('#mapOverlay').hidden) return; const horizontal = (state.keys.arrowright || state.keys.d ? 1 : 0) - (state.keys.arrowleft || state.keys.a ? 1 : 0); const vertical = (state.keys.arrowdown || state.keys.s ? 1 : 0) - (state.keys.arrowup || state.keys.w ? 1 : 0); if (!horizontal && !vertical) return; const length = Math.hypot(horizontal, vertical) || 1; const speed = (state.policeChase ? .014 : .011) * delta; state.player.x = Math.max(6, Math.min(94, state.player.x + horizontal / length * speed)); state.player.y = Math.max(30, Math.min(88, state.player.y + vertical / length * speed * .7)); updateNearby(); renderStreet(); }
let lastMovementFrame = performance.now();
function movementLoop(timestamp) { const delta = Math.min(50, timestamp - lastMovementFrame); lastMovementFrame = timestamp; updatePlayerMovement(delta); updatePoliceChase(delta); requestAnimationFrame(movementLoop); }
function nextDay() { if (state.day >= 12) { endGame(); return; } state.day += 1; makePrices(); generateCustomers(); state.saleTarget = null; state.nearbyCustomer = null; state.inWorld = false; state.nightSales = 0; state.taskSales = 0; state.taskBuys = 0; state.taskTravel = 0; state.combo = 0; state.nightGoal = 2 + Math.floor(Math.random() * 3); state.nightBonus = 350 + Math.floor(Math.random() * 4) * 100; state.contract = { ...contractTemplates[Math.floor(Math.random() * contractTemplates.length)] }; state.risk = Math.max(4, state.risk + Math.round((Math.random() - .38) * 10)); const events = ['En leverance blev forsinket. Priserne hopper.', 'En ny kunde spreder dit navn i byen.', 'Nogen har set for meget. Hold lav profil.', 'Markedet er mærkeligt roligt i nat.']; const event = events[Math.floor(Math.random() * events.length)]; $('#eventText').textContent = event; addLog(`Dag ${String(state.day).padStart(2, '0')}: ${event} Nye kontakter er dukket op.`); render(); toast(`Dag ${String(state.day).padStart(2, '0')} er begyndt`); }
function endGame() { const score = state.cash + state.rep * 100 - state.risk * 15; $('#eventText').textContent = `Din 12-dages rute er slut. Slutscore: ${format(score)}.`; $('#statusText').textContent = 'RUTEN SLUT'; $('#nextDayBtn').querySelector('span').textContent = 'Spil igen'; $('#nextDayBtn').onclick = reset; toast(`Slutscore: ${format(score)}`); }
function reset() { state.cash = 2500; state.day = 1; state.rep = 12; state.risk = 18; state.inventory = {}; state.player = { x: 50, y: 73 }; state.keys = {}; state.nearbyCustomer = null; state.saleTarget = null; state.activeTab = 'sell'; state.inWorld = true; state.nightSales = 0; state.nightGoal = 3; state.nightBonus = 500; state.taskSales = 0; state.taskBuys = 0; state.taskTravel = 0; state.combo = 0; state.comboBest = 0; state.contract = { ...contractTemplates[0] }; state.ownedCustomizations = []; state.ownedUpgrades = []; state.equipped = { hat: '', shirt: '', pants: '', emote: '', textile: '' }; state.shopCategory = 'ALLE'; state.logs = []; generateCustomers(); makePrices(); $('#statusText').textContent = 'MARKED OPEN'; $('#nextDayBtn').querySelector('span').textContent = 'Afslut dag'; $('#nextDayBtn').onclick = nextDay; $('#eventText').textContent = 'Markedet er roligt. Brug din fordel, mens den varer.'; addLog('Ny rute aabnet. Du har 12 dage.'); render(); }
function renderLog() { $('#activityLog').innerHTML = state.logs.map((log, index) => `<div class="log-item"><b>${String(index + 1).padStart(2, '0')}</b><span>${log.text}</span></div>`).join(''); $('#logCount').textContent = String(state.logs.length).padStart(2, '0'); }
function render() { $('#cash').textContent = format(state.cash); $('#day').textContent = `${String(state.day).padStart(2, '0')} / 12`; $('#dayMeta').textContent = ['tirsdag','onsdag','torsdag','fredag','lørdag','søndag','mandag'][(state.day - 1) % 7] + ', 22:40'; $('#rep').textContent = state.rep; $('#inventoryCount').textContent = inventoryTotal(); $('#inventoryBar').style.width = `${inventoryTotal() / 24 * 100}%`; $('#sellBadge').textContent = inventoryTotal(); $('#goalText').textContent = `Lav ${state.nightGoal} handler`; $('#goalProgress').textContent = `${Math.min(state.nightSales, state.nightGoal)} / ${state.nightGoal} handler · bonus ${format(state.nightBonus)}`; $('#goalBar').style.width = `${Math.min(100, state.nightSales / state.nightGoal * 100)}%`; $('#taskList').innerHTML = `<div class="task-row"><span>Gennemfør handler</span><b>${Math.min(state.taskSales, 8)} / 8</b></div><div class="task-row"><span>Køb varer</span><b>${Math.min(state.taskBuys, 15)} / 15</b></div><div class="task-row"><span>Rejs mellem områder</span><b>${Math.min(state.taskTravel, 3)} / 3</b></div><div class="task-row combo-row"><span>Combo / bedste</span><b>${state.combo}x / ${state.comboBest}x</b></div>${state.contract ? `<div class="contract-row"><span>${state.contract.title}</span><b>${Math.min(state.taskSales, state.contract.target)} / ${state.contract.target}</b></div>` : ''}`; $('#riskValue').textContent = `${state.risk}%`; $('#riskBar').style.width = `${state.risk}%`; $('#locationLabel').textContent = `POSITION: ${districts[state.location].name.toUpperCase()}`; $('#sellLocationPosition').textContent = `POSITION: ${districts[state.location].name.toUpperCase()}`; $('#marketTitle').textContent = districts[state.location].name; renderDistricts(); renderGoods(); renderStreet(); setTab(state.activeTab); if (state.saleTarget) renderQuickSale(); else $('#saleOverlay').hidden = true; }
function decorateShopSales() { document.querySelectorAll('.shop-item').forEach((itemNode) => { const buyButton = itemNode.querySelector('[data-customization]'); if (!buyButton || itemNode.querySelector('[data-sell-customization]')) return; const item = customizationItems.find((entry) => entry.id === buyButton.dataset.customization); if (!item || !state.ownedCustomizations.includes(item.id)) return; const sellButton = document.createElement('button'); sellButton.className = 'sell-customization'; sellButton.dataset.sellCustomization = item.id; sellButton.textContent = `SÆLG ${format(Math.floor(item.price * .6))}`; sellButton.addEventListener('click', () => sellCustomization(item.id)); itemNode.appendChild(sellButton); }); }
new MutationObserver(decorateShopSales).observe($('#shopItems'), { childList: true, subtree: true }); setInterval(decorateShopSales, 500);
$('#interactBtn').addEventListener('click', interact); $('#returnMap').addEventListener('click', openMap); $('#profileShopLink').addEventListener('click', () => setTab('shop')); $('#profileLogout').addEventListener('click', () => window.logoutSupabase && window.logoutSupabase());
document.querySelectorAll('.game-tab').forEach((button) => button.addEventListener('click', () => setTab(button.dataset.tab)));
$('#mapBtn').addEventListener('click', openMap); $('#mapClose').addEventListener('click', closeMap);
window.addEventListener('keydown', (event) => { const key = event.key.toLowerCase(); const target = event.target; const typing = target.matches('input, textarea, select, [contenteditable="true"]'); if (typing) return; if (state.arrestMinigame && key === 'e') { event.preventDefault(); resolveArrestMinigame(); return; } if (['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s'].includes(key)) { event.preventDefault(); state.keys[key] = true; } if (key === 'e' || key === ' ') { event.preventDefault(); interact(); } });
window.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !$('#mapOverlay').hidden) closeMap(); else if (event.key === 'Escape' && state.saleTarget) closeSale(); });
window.addEventListener('keyup', (event) => { const target = event.target; if (target.matches('input, textarea, select, [contenteditable="true"]')) return; state.keys[event.key.toLowerCase()] = false; });
window.addEventListener('blur', clearMovementInput);
document.addEventListener('visibilitychange', () => { if (document.hidden) clearMovementInput(); });
document.querySelectorAll('[data-move]').forEach((button) => { const key = button.dataset.move; button.addEventListener('pointerdown', () => { state.keys[key] = true; }); button.addEventListener('pointerup', () => { state.keys[key] = false; }); button.addEventListener('pointerleave', () => { state.keys[key] = false; }); });
$('#saleClose').addEventListener('click', closeSale); $('#wastedClose').addEventListener('click', () => { $('#wastedOverlay').hidden = true; $('#escapeOverlay').hidden = true; state.arrestMinigame = null; $('#policeNpc').hidden = true; render(); toast('Du er fri igen — byg lageret op på ny'); });
setInterval(moveCustomers, 850); setInterval(() => { const unpaidBefore = state.postMessages.filter((message) => !message.paid).length; checkPostDeadlines(); if (unpaidBefore > state.postMessages.filter((message) => !message.paid).length) render(); }, 1000);
requestAnimationFrame(movementLoop);
$('#nextDayBtn').addEventListener('click', () => { if (state.loan > 0 && state.day < 12) { const interest = Math.ceil(state.loan * state.loanRate); state.loan += interest; addLog(`Banken lagde ${format(interest)} i rente på dit lån.`); } }); $('#nextDayBtn').addEventListener('click', nextDay); $('#newGameBtn').addEventListener('click', () => { state.loan = 0; }); $('#newGameBtn').addEventListener('click', reset); $('#takeLoan').addEventListener('click', takeLoan); $('#repayLoan').addEventListener('click', repayLoan); reset();
